### ISSUE TITLE
Add Shift Register style OSRAM support to this project

### ISSUE THREAD

**Issue by beau-williamson** [uriba107/deduino#3]
We could really use Shift Register style OSRAM 4 and 8 character 5x7 support.  These are used in the CMDS, EWMU, EWMP and other places in the pit.  I'm hoping this can be added as part of the DEDuino project.  The Shift Register OSRAMs also require character tables to display things on the OSRAM so I suspect there is some duplication that can be used.  Please contact Henkie on VP to see how he interfaced some of the HCMS-2913 OSRAMs to PICs (Due should do the trick too) for his FQI.  The reason these Shift Register style OSRAMs are used is that the SLG2016 OSRAMs are no longer available and pretty much all alternatives are the Shift Register style. Here's the link to how Henkie built his FQI. http://www.pdp-11.nl/viperpit/fqi/fuel-quantity-ind.html.  If OSRAMs can be added, it will fill one of the last gaps in building F16 pits.

Here's the spec sheet on the OSRAMs Henkie used.
[Broadcom HCMS-29xx 4&8 Char 5x7 Matrix Serial display.pdf](https://github.com/uriba107/deduino/files/3096881/Broadcom.HCMS-29xx.4.8.Char.5x7.Matrix.Serial.display.pdf)

Beau "Willy" Williamson

**Comment by uriba107** [comment]
I'm no longer actively developing this project. So new features will not happen. Sorry 😟
